name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.0.1
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://win32.pub

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.4
  test_coverage: ^0.5.0
  # winmd: ^0.4.0-dev.7

dependency_overrides:
  winmd:
    path: ../winmd