name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # Include newest and latest versions of Windows, plus Ubuntu (to make
        # sure that tests don't fail on a non-supported platform).
        os: [windows-latest, windows-2016, ubuntu-latest]
        # Stable does not support null safety yet.
        # sdk: [stable, beta, dev, edge]
        sdk: [beta, dev, edge]
      fail-fast: false

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: cedx/setup-dart@v2
        with:
          architecture: x64
          release-channel: ${{matrix.sdk}}
          version: latest

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: dart analyze

      - name: Run tests
        run: dart test
